### ISSUE TITLE
Wrong script

### ISSUE THREAD

**Issue by Nipers** [acharkq/MolCA#7]
It is really upset to find that there are some differences between script in readme and the chebi.sh under directory "script" when I have got results by running the later script, which has no opeartion to load pretrained checkpionts, and the results is very similar to your reported performance. I' d like to explore whether the pretrain  stage is meaningful for caption task on chebi dataset. Please edit chebi.sh to right version.

**Comment by acharkq** [comment]
Thanks for the interest in our work, and sorry for the inconvenience caused by the incorrect script under the script folder. The correct script to load stage-2 checkpoint and fine-tune for chebi-20 is 

```bash
{
export TOKENIZERS_PARALLELISM=false;

python stage2.py --root 'data/ChEBI-20_data' --devices '0,1' --filename "ft_chebi"  --opt_model 'facebook/galactica-1.3b' --max_epochs 100 --mode ft --prompt '[START_I_SMILES]{}[END_I_SMILES]. ' --tune_gnn --llm_tune lora --inference_batch_size 8 --peft_config lora_config.json --caption_eval_epoch 10 --stage2_path path-to-stage2-ckpt
exit
}
```

You can download our pretrained stage 2 checkpoint from this huggingface repo: https://huggingface.co/acharkq/MolCA/tree/main

As for your observed limited improvement from the pretraining phase, it might be attributed to the following factor: the effectiveness of the pretraining phase is dependent on the distribution shift between the pretrain dataset and the downstream dataset. The improvement will be smaller when the pretrain dataset is less similar to the downstream dataset.

**Comment by DingYX0731** [comment]
How to obtain `adapter_model.bin` after fine-tuning?
