### ISSUE TITLE
Conda Environment Error

### ISSUE THREAD

**Issue by Ryoo72** [acharkq/MolCA#8]
Hello, thank you for your interesting research. As instructed in the Readme, I executed `conda env remove -n molca`, but encountered the following error:

~~~
Requirement already satisfied: scikit-learn>=0.20.0 in /opt/conda/envs/molca/lib/python3.8/site-packages (from ogb==1.3.6->-r /shared/workspace/MolCA/condaenv.ni31lhb3.requirements.txt (line 94)) (1.2.2)
Collecting sklearn
Using cached sklearn-0.0.post12.tar.gz (2.6 kB)
Preparing metadata (setup.py): started
Preparing metadata (setup.py): finished with status 'error'

Pip subprocess error:
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
      rather than 'sklearn' for pip commands.
      
      Here is how to fix this error in the main use cases:
      - use 'pip install scikit-learn' rather than 'pip install sklearn'
      - replace 'sklearn' by 'scikit-learn' in your pip requirements files
        (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
      - if the 'sklearn' package is used by one of your dependencies,
        it would be great if you take some time to track which package uses
        'sklearn' instead of 'scikit-learn' and report it to their issue tracker
      - as a last resort, set the environment variable
        SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error
      
      More information is available at
      https://github.com/scikit-learn/sklearn-pypi-package
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

failed

CondaEnvException: Pip failed
~~~

Below is the Dockerfile I used:

~~~Docker
FROM nvidia/cuda:11.7.1-cudnn8-devel-ubuntu20.04

# Install base utilities
RUN apt-get update \
    && apt-get install -y build-essential \
    && apt-get install -y wget \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install miniconda
ENV CONDA_DIR /opt/conda
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p /opt/conda

# Put conda in path so we can use conda activate
ENV PATH=$CONDA_DIR/bin:$PATH
~~~

Is there anything I might be missing? Thank you.

**Comment by ScottLiao920** [comment]
I got the same problem for `conda env remove -n molca` here without using docker. Appreciate any possible solutions.

**Comment by Ryoo72** [comment]
not yet 🥲

**Comment by acharkq** [comment]
Thank you for your interests in our work. This problem might be caused by certain package version issues, due to the package's update. Can you try the following steps for creating a new environment? These steps work for me on my machine with A100 GPUs. If you find these steps work as well, I will update them into the github repo

* conda create -n molca python=3.8

* conda activate molca

* conda install pytorch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 pytorch-cuda=11.7 -c pytorch -c nvidia
* conda install pyg -c pyg

* pip install git+https://github.com/thunlp/OpenDelta.git

* pip install rouge_score nltk salesforce-lavis

* pip install -U transformers pytorch-lightning 

* pip install deepspeed
* Download nltk corpus:

```
import nltk

nltk.download('wordnet')
```

**Comment by Ryoo72** [comment]
cool I'll try it rn

**Comment by acharkq** [comment]
Hi Scott, Thanks for the response. I will include ogb, peft and rdkit as well in the instruction for setup environment.

As for the import error, please ensure to install `transformers` after installing `salesforce-lavis`. This is because `salesforce-lavis` will force install an older version of `transformers`. You should be able to fix this problem by running `pip install -U transformers`

**Comment by acharkq** [comment]
Let me know if this can fix the import error issue.

**Comment by Ryoo72** [comment]
Pretrain stage 1 works well. It's a minor comment, but the name needs to be changed from `train.pt` to `PubChem324ktrain.pt` in Pretrain Stage 1. Also, the environment is set up by running apt-get update & apt-get install git. Thank you very much for the prompt reply. I will try Stage 2 as well.

**Comment by ScottLiao920** [comment]
I think a more elegant way is to change the command from `python stage1.py --root 'data/PubChem324kV2' --gtm --lm --devices '0,1' --mode train --filename stage1 --rerank_cand_num 128 --num_query_token 8 --tune_gnn` to `python stage1.py --root 'data/PubChem324kV2/' --gtm --lm --devices '0,1' --mode train --filename stage1 --rerank_cand_num 128 --num_query_token 8 --tune_gnn`
with a slash after the data directory

**Comment by Ryoo72** [comment]
oh great thx alot
